-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 13:57:38 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda` DEFAULT CHARACTER SET utf8 ;
USE `tienda` ;

-- -----------------------------------------------------
-- Table `tienda`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `password` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `rol` INT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `role_idx` (`rol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`Permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Permission` (
  `idPermission` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`idPermission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `description` LONGTEXT NULL,
  `picture` VARCHAR(250) NULL,
  `price` FLOAT NULL,
  `available` INT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`Purchase` (
  `idPurchase` INT NOT NULL AUTO_INCREMENT,
  `buyerId` INT NULL,
  `sellerId` INT NULL,
  `date` DATETIME NULL,
  `total` FLOAT NULL,
  PRIMARY KEY (`idPurchase`),
  INDEX `buyer_idx` (`buyerId` ASC),
  INDEX `seller_idx` (`sellerId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`PurchaseDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`PurchaseDetails` (
  `idPurchaseDetails` INT NOT NULL AUTO_INCREMENT,
  `idPurchase` INT NULL,
  `idProduct` INT NULL,
  `quantity` INT NULL,
  INDEX `purchase_idx` (`idPurchase` ASC),
  INDEX `product_idx` (`idProduct` ASC),
  PRIMARY KEY (`idPurchaseDetails`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda`.`RolesPermissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda`.`RolesPermissions` (
  `idRolesPermissions` INT NOT NULL AUTO_INCREMENT,
  `idRole` INT NOT NULL,
  `idPermission` INT NOT NULL,
  INDEX `role_idx` (`idRole` ASC),
  INDEX `permision_idx` (`idPermission` ASC),
  PRIMARY KEY (`idRolesPermissions`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
